### ISSUE TITLE
Cannot enter the app, it asks for a play store license, but there is no application in the play store

### ISSUE THREAD

**Issue by anarchist22** [naveenccmsd/Ayan#1]
![Screenshot_20230106-122939_Ayan.jpg](https://user-images.githubusercontent.com/71122765/211065640-9bb73966-b844-45b6-82f7-117532bc1311.jpg)

**Comment by naveenccmsd** [comment]
@anarchist22 Thanks for raising the issue. it has fixed in [v1.2.2](https://github.com/naveenccmsd/Ayan/releases/tag/1.2.2).
